### ISSUE TITLE
Refit CICD Pipeline YAML

### ISSUE THREAD

**Issue by rutalreja-deloitte** [GoogleCloudPlatform/terraform-example-foundation-app#23]
The app cloud build yaml steps need to be checked and the entire file needs more fine-tooth combing/ remove unnecessary lines comments/ repeated logic etc.
This will also help form the readme for app build as current readme lacks details on any and all steps performed.

**Comment by bharathkkb** [comment]
as we own the k8s manifests we should also consider switching them to kpt packages with setters.
