### ISSUE TITLE
Bank of Anthos APP automatically redirect to HTTPS 

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-example-foundation-app#60]
## Expected Behavior

When I use Bank of Anthos following the instructions it does not configure SSL and I should navigate in http

## Actual Behavior

When we navigate we are redirected to HTTPS and we get a not found because we don't have HTTPS enable.

## Steps to Reproduce the Problem

1. Follow the instructions up to step 6-anthos-install
1. Access the application using the public ip http://<Public IP>
2. click in any of the links

## Specifications

- Version: 5b02673ce839e2ec0f35b2039f57d365e3fbcab9
- Platform: Ubuntu 20.04

**Comment by daniel-cit** [comment]
This value must be changed to "http" to prevent the redirection.


https://github.com/GoogleCloudPlatform/terraform-example-foundation-app/blob/5b02673ce839e2ec0f35b2039f57d365e3fbcab9/6-anthos-install/acm-repos/frontend/frontend.yaml#L46-L47

This should be changed before pushing the configuration.

**Comment by dkassab** [comment]
We discussed this during our session today. Let's just use "http"
