### ISSUE TITLE
Create a troubleshooting to step 6 and add authorization git problem

### ISSUE THREAD

**Issue by vfigueiredo-cit** [GoogleCloudPlatform/terraform-example-foundation-app#85]
## Expected Behavior
Get authorization to access git repositories from bastion.

## Actual Behavior
When using your personal account to access git repositories on bastion, it is not authorized.
Error:
```
fatal: unable to access 'https://source.developers.google.com/p/prj-bu1-c-app-cicd-a72f/r/root-config-repo/': The requested URL returned error: 400
ERROR: (gcloud.source.repos.clone) Command '[u'git', u'clone', u'https://source.developers.google.com/p/prj-bu1-c-app-cicd-a72f/r/root-config-repo', u'/home/ext_vfigueiredo_ciandt_com/bank-of-anthos-repos/root-config-repo']' returned non-zero exit status 128
```

## Steps to Reproduce the Problem

1. Deploy foundation-app up to step 6-anthos-install
1. On bastion, try to access(clone, push, etc) a git repository
1.

## Sugestion
To authorize it, is necessary to have an accredited service account in addition to the validation token, which expires in around 30 minutes and it is necessary to generate a new one.

To list Credentialed Accounts:
```
gcloud auth list
```

To generate the token:
```
gcloud auth print-access-token
```

Use the credentials obtained when access git repositories.

## Specifications

- Version: ce45993
- Platform: Ubuntu 20.04.2 LTS

**Comment by rutalreja-deloitte** [comment]
the bastion sa has [permission](https://github.com/GoogleCloudPlatform/terraform-example-foundation-app/blob/main/5-infrastructure/modules/bastion/main.tf#L60) to access the repo, if you want your personal account to have access you will need to manually do that. It is assumed the user will use the default auth (bastion-sa) to perform actions on the bastion VM.
