### ISSUE TITLE
terraform-example-foundation-app/6-anthos-install/db-scripts/populate-ledger-db.yaml" does not exist

### ISSUE THREAD

**Issue by sganesanmuth** [GoogleCloudPlatform/terraform-example-foundation-app#96]
When I try to execute below command
kubectl apply -n transactions --context ${CTX_1} -f ${HOME}/terraform-example-foundation-app/6-anthos-install/db-scripts/populate-ledger-db.yaml

`error: the path "/home/XXXX/terraform-example-foundation-app/6-anthos-install/db-scripts/populate-ledger-db.yaml" does not exist`

Looks like above mentioned file is not available in the repo.
Any idea how to generate that populate-ledger-db.yaml file

**Comment by markmacmahon** [comment]
https://github.com/GoogleCloudPlatform/terraform-example-foundation-app/pull/50#issuecomment-838964462
